site_name: Cofe Cream
theme:
  name: material

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: red 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  
extra:
 social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_7jIAGV-C-IUZh6kmeOToQ
    - icon: fontawesome/brands/discord
      link: https://discord.gg/PgH2aQd4bY


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/raynoxgame/Cofe-Cream-Official"  target="_blank" rel="noopener">Cofe Cream Official</a>